-- TODO: Generated by Opus 4.5 and not yet verified

local Deathless = Deathless

Deathless.Data = Deathless.Data or {}
Deathless.Data.Abilities = Deathless.Data.Abilities or {}

-- base_cost is stored in copper (1 silver = 100 copper, 1 gold = 10000 copper)
-- Actual cost may be reduced by reputation discounts (5% honored, 10% revered, 15% exalted)
-- Source types:
--   trainer - Learned from class trainer
--   talent  - Requires 31-point talent (only shown if base talent is learned)
--   class   - Innate class ability (learned automatically)
--   book    - Learned from a drop/item
--   quest   - Learned from completing a quest
-- Optional fields:
--   faction - "Alliance" or "Horde" (for faction-specific spells like teleports/portals)
-- Sorted alphabetically by name, then by rank
-- See https://www.wowhead.com/classic/spells/abilities/mage for source data
Deathless.Data.Abilities["Mage"] = {
    -- Amplify Magic
    { name = "Amplify Magic", level = 18, rank = 1, base_cost = 1800, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Amplify Magic", level = 30, rank = 2, base_cost = 8000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Amplify Magic", level = 42, rank = 3, base_cost = 18000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Amplify Magic", level = 54, rank = 4, base_cost = 36000, icon = "Spell_Holy_FlashHeal", source = "trainer" },

    -- Arcane Brilliance (book)
    { name = "Arcane Brilliance", level = 56, rank = 1, base_cost = 0, icon = "Spell_Holy_ArcaneIntellect", source = "book" },

    -- Arcane Explosion
    { name = "Arcane Explosion", level = 14, rank = 1, base_cost = 900, icon = "Spell_Nature_WispSplode", source = "trainer" },
    { name = "Arcane Explosion", level = 22, rank = 2, base_cost = 3000, icon = "Spell_Nature_WispSplode", source = "trainer" },
    { name = "Arcane Explosion", level = 30, rank = 3, base_cost = 8000, icon = "Spell_Nature_WispSplode", source = "trainer" },
    { name = "Arcane Explosion", level = 38, rank = 4, base_cost = 14000, icon = "Spell_Nature_WispSplode", source = "trainer" },
    { name = "Arcane Explosion", level = 46, rank = 5, base_cost = 26000, icon = "Spell_Nature_WispSplode", source = "trainer" },
    { name = "Arcane Explosion", level = 54, rank = 6, base_cost = 36000, icon = "Spell_Nature_WispSplode", source = "trainer" },

    -- Arcane Intellect
    { name = "Arcane Intellect", level = 1, rank = 1, base_cost = 10, icon = "Spell_Holy_MagicalSentry", source = "trainer" },
    { name = "Arcane Intellect", level = 14, rank = 2, base_cost = 900, icon = "Spell_Holy_MagicalSentry", source = "trainer" },
    { name = "Arcane Intellect", level = 28, rank = 3, base_cost = 7000, icon = "Spell_Holy_MagicalSentry", source = "trainer" },
    { name = "Arcane Intellect", level = 42, rank = 4, base_cost = 18000, icon = "Spell_Holy_MagicalSentry", source = "trainer" },
    { name = "Arcane Intellect", level = 56, rank = 5, base_cost = 38000, icon = "Spell_Holy_MagicalSentry", source = "trainer" },

    -- Arcane Missiles
    { name = "Arcane Missiles", level = 8, rank = 1, base_cost = 200, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 16, rank = 2, base_cost = 1500, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 24, rank = 3, base_cost = 4000, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 32, rank = 4, base_cost = 10000, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 40, rank = 5, base_cost = 15000, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 48, rank = 6, base_cost = 28000, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 56, rank = 7, base_cost = 38000, icon = "Spell_Nature_StarFall", source = "trainer" },
    { name = "Arcane Missiles", level = 60, rank = 8, base_cost = 42000, icon = "Spell_Nature_StarFall", source = "trainer" },

    -- Arcane Power (Arcane 31-point talent)
    { name = "Arcane Power", level = 40, rank = 1, base_cost = 0, icon = "Spell_Nature_Lightning", source = "talent" },

    -- Blast Wave (Fire 21-point talent)
    { name = "Blast Wave", level = 30, rank = 1, base_cost = 0, icon = "Spell_Holy_Excorcism_02", source = "talent" },
    { name = "Blast Wave", level = 36, rank = 2, base_cost = 650, icon = "Spell_Holy_Excorcism_02", source = "talent" },
    { name = "Blast Wave", level = 44, rank = 3, base_cost = 1150, icon = "Spell_Holy_Excorcism_02", source = "talent" },
    { name = "Blast Wave", level = 52, rank = 4, base_cost = 1750, icon = "Spell_Holy_Excorcism_02", source = "talent" },
    { name = "Blast Wave", level = 60, rank = 5, base_cost = 2100, icon = "Spell_Holy_Excorcism_02", source = "talent" },

    -- Blink
    { name = "Blink", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Arcane_Blink", source = "trainer" },

    -- Blizzard
    { name = "Blizzard", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Frost_IceStorm", source = "trainer" },
    { name = "Blizzard", level = 28, rank = 2, base_cost = 7000, icon = "Spell_Frost_IceStorm", source = "trainer" },
    { name = "Blizzard", level = 36, rank = 3, base_cost = 13000, icon = "Spell_Frost_IceStorm", source = "trainer" },
    { name = "Blizzard", level = 44, rank = 4, base_cost = 23000, icon = "Spell_Frost_IceStorm", source = "trainer" },
    { name = "Blizzard", level = 52, rank = 5, base_cost = 35000, icon = "Spell_Frost_IceStorm", source = "trainer" },
    { name = "Blizzard", level = 60, rank = 6, base_cost = 42000, icon = "Spell_Frost_IceStorm", source = "trainer" },

    -- Cold Snap (Frost 11-point talent)
    { name = "Cold Snap", level = 20, rank = 1, base_cost = 0, icon = "Spell_Frost_WizardMark", source = "talent" },

    -- Combustion (Fire 31-point talent)
    { name = "Combustion", level = 40, rank = 1, base_cost = 0, icon = "Spell_Fire_SealOfFire", source = "talent" },

    -- Cone of Cold
    { name = "Cone of Cold", level = 26, rank = 1, base_cost = 5000, icon = "Spell_Frost_Glacier", source = "trainer" },
    { name = "Cone of Cold", level = 34, rank = 2, base_cost = 12000, icon = "Spell_Frost_Glacier", source = "trainer" },
    { name = "Cone of Cold", level = 42, rank = 3, base_cost = 18000, icon = "Spell_Frost_Glacier", source = "trainer" },
    { name = "Cone of Cold", level = 50, rank = 4, base_cost = 32000, icon = "Spell_Frost_Glacier", source = "trainer" },
    { name = "Cone of Cold", level = 58, rank = 5, base_cost = 40000, icon = "Spell_Frost_Glacier", source = "trainer" },

    -- Conjure Food
    { name = "Conjure Food", level = 6, rank = 1, base_cost = 100, icon = "INV_Misc_Food_09", source = "trainer" },
    { name = "Conjure Food", level = 12, rank = 2, base_cost = 600, icon = "INV_Misc_Food_09", source = "trainer" },
    { name = "Conjure Food", level = 22, rank = 3, base_cost = 3000, icon = "INV_Misc_Food_09", source = "trainer" },
    { name = "Conjure Food", level = 32, rank = 4, base_cost = 10000, icon = "INV_Misc_Food_09", source = "trainer" },
    { name = "Conjure Food", level = 42, rank = 5, base_cost = 18000, icon = "INV_Misc_Food_09", source = "trainer" },
    { name = "Conjure Food", level = 52, rank = 6, base_cost = 35000, icon = "INV_Misc_Food_09", source = "trainer" },

    -- Conjure Mana Agate
    { name = "Conjure Mana Agate", level = 28, rank = 1, base_cost = 7000, icon = "INV_Misc_Gem_Emerald_02", source = "trainer" },

    -- Conjure Mana Citrine
    { name = "Conjure Mana Citrine", level = 48, rank = 1, base_cost = 28000, icon = "INV_Misc_Gem_Opal_01", source = "trainer" },

    -- Conjure Mana Jade
    { name = "Conjure Mana Jade", level = 38, rank = 1, base_cost = 14000, icon = "INV_Misc_Gem_Emerald_01", source = "trainer" },

    -- Conjure Mana Ruby
    { name = "Conjure Mana Ruby", level = 58, rank = 1, base_cost = 40000, icon = "INV_Misc_Gem_Ruby_01", source = "trainer" },

    -- Conjure Water
    { name = "Conjure Water", level = 4, rank = 1, base_cost = 100, icon = "INV_Drink_07", source = "trainer" },
    { name = "Conjure Water", level = 10, rank = 2, base_cost = 400, icon = "INV_Drink_07", source = "trainer" },
    { name = "Conjure Water", level = 20, rank = 3, base_cost = 2000, icon = "INV_Drink_07", source = "trainer" },
    { name = "Conjure Water", level = 30, rank = 4, base_cost = 8000, icon = "INV_Drink_07", source = "trainer" },
    { name = "Conjure Water", level = 40, rank = 5, base_cost = 15000, icon = "INV_Drink_07", source = "trainer" },
    { name = "Conjure Water", level = 50, rank = 6, base_cost = 32000, icon = "INV_Drink_07", source = "trainer" },
    { name = "Conjure Water", level = 60, rank = 7, base_cost = 42000, icon = "INV_Drink_07", source = "trainer" },

    -- Counterspell
    { name = "Counterspell", level = 24, rank = 1, base_cost = 4000, icon = "Spell_Frost_IceShock", source = "trainer" },

    -- Dampen Magic
    { name = "Dampen Magic", level = 12, rank = 1, base_cost = 600, icon = "Spell_Nature_AbolishMagic", source = "trainer" },
    { name = "Dampen Magic", level = 24, rank = 2, base_cost = 4000, icon = "Spell_Nature_AbolishMagic", source = "trainer" },
    { name = "Dampen Magic", level = 36, rank = 3, base_cost = 13000, icon = "Spell_Nature_AbolishMagic", source = "trainer" },
    { name = "Dampen Magic", level = 48, rank = 4, base_cost = 28000, icon = "Spell_Nature_AbolishMagic", source = "trainer" },
    { name = "Dampen Magic", level = 60, rank = 5, base_cost = 42000, icon = "Spell_Nature_AbolishMagic", source = "trainer" },

    -- Detect Magic
    { name = "Detect Magic", level = 16, rank = 1, base_cost = 1500, icon = "Spell_Holy_Dizzy", source = "trainer" },

    -- Evocation
    { name = "Evocation", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Nature_Purge", source = "trainer" },

    -- Fire Blast
    { name = "Fire Blast", level = 6, rank = 1, base_cost = 100, icon = "Spell_Fire_Fireball", source = "trainer" },
    { name = "Fire Blast", level = 14, rank = 2, base_cost = 900, icon = "Spell_Fire_Fireball", source = "trainer" },
    { name = "Fire Blast", level = 22, rank = 3, base_cost = 3000, icon = "Spell_Fire_Fireball", source = "trainer" },
    { name = "Fire Blast", level = 30, rank = 4, base_cost = 8000, icon = "Spell_Fire_Fireball", source = "trainer" },
    { name = "Fire Blast", level = 38, rank = 5, base_cost = 14000, icon = "Spell_Fire_Fireball", source = "trainer" },
    { name = "Fire Blast", level = 46, rank = 6, base_cost = 26000, icon = "Spell_Fire_Fireball", source = "trainer" },
    { name = "Fire Blast", level = 54, rank = 7, base_cost = 36000, icon = "Spell_Fire_Fireball", source = "trainer" },

    -- Fire Ward
    { name = "Fire Ward", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Fire_FireArmor", source = "trainer" },
    { name = "Fire Ward", level = 30, rank = 2, base_cost = 8000, icon = "Spell_Fire_FireArmor", source = "trainer" },
    { name = "Fire Ward", level = 40, rank = 3, base_cost = 15000, icon = "Spell_Fire_FireArmor", source = "trainer" },
    { name = "Fire Ward", level = 50, rank = 4, base_cost = 32000, icon = "Spell_Fire_FireArmor", source = "trainer" },
    { name = "Fire Ward", level = 60, rank = 5, base_cost = 42000, icon = "Spell_Fire_FireArmor", source = "trainer" },

    -- Fireball (innate)
    { name = "Fireball", level = 1, rank = 1, base_cost = 0, icon = "Spell_Fire_FlameBolt", source = "class" },
    { name = "Fireball", level = 6, rank = 2, base_cost = 100, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 12, rank = 3, base_cost = 600, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 18, rank = 4, base_cost = 1800, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 24, rank = 5, base_cost = 4000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 30, rank = 6, base_cost = 8000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 36, rank = 7, base_cost = 13000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 42, rank = 8, base_cost = 18000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 48, rank = 9, base_cost = 28000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 54, rank = 10, base_cost = 36000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 60, rank = 11, base_cost = 42000, icon = "Spell_Fire_FlameBolt", source = "trainer" },
    { name = "Fireball", level = 60, rank = 12, base_cost = 0, icon = "Spell_Fire_FlameBolt", source = "book" },

    -- Flamestrike
    { name = "Flamestrike", level = 16, rank = 1, base_cost = 1500, icon = "Spell_Fire_SelfDestruct", source = "trainer" },
    { name = "Flamestrike", level = 24, rank = 2, base_cost = 4000, icon = "Spell_Fire_SelfDestruct", source = "trainer" },
    { name = "Flamestrike", level = 32, rank = 3, base_cost = 10000, icon = "Spell_Fire_SelfDestruct", source = "trainer" },
    { name = "Flamestrike", level = 40, rank = 4, base_cost = 15000, icon = "Spell_Fire_SelfDestruct", source = "trainer" },
    { name = "Flamestrike", level = 48, rank = 5, base_cost = 28000, icon = "Spell_Fire_SelfDestruct", source = "trainer" },
    { name = "Flamestrike", level = 56, rank = 6, base_cost = 38000, icon = "Spell_Fire_SelfDestruct", source = "trainer" },

    -- Frost Armor (innate)
    { name = "Frost Armor", level = 1, rank = 1, base_cost = 0, icon = "Spell_Frost_FrostArmor02", source = "class" },
    { name = "Frost Armor", level = 10, rank = 2, base_cost = 400, icon = "Spell_Frost_FrostArmor02", source = "trainer" },
    { name = "Frost Armor", level = 20, rank = 3, base_cost = 2000, icon = "Spell_Frost_FrostArmor02", source = "trainer" },

    -- Frost Nova
    { name = "Frost Nova", level = 10, rank = 1, base_cost = 400, icon = "Spell_Frost_FrostNova", source = "trainer" },
    { name = "Frost Nova", level = 26, rank = 2, base_cost = 5000, icon = "Spell_Frost_FrostNova", source = "trainer" },
    { name = "Frost Nova", level = 40, rank = 3, base_cost = 15000, icon = "Spell_Frost_FrostNova", source = "trainer" },
    { name = "Frost Nova", level = 54, rank = 4, base_cost = 36000, icon = "Spell_Frost_FrostNova", source = "trainer" },

    -- Frost Ward
    { name = "Frost Ward", level = 22, rank = 1, base_cost = 3000, icon = "Spell_Frost_FrostWard", source = "trainer" },
    { name = "Frost Ward", level = 32, rank = 2, base_cost = 10000, icon = "Spell_Frost_FrostWard", source = "trainer" },
    { name = "Frost Ward", level = 42, rank = 3, base_cost = 18000, icon = "Spell_Frost_FrostWard", source = "trainer" },
    { name = "Frost Ward", level = 52, rank = 4, base_cost = 35000, icon = "Spell_Frost_FrostWard", source = "trainer" },

    -- Frostbolt
    { name = "Frostbolt", level = 4, rank = 1, base_cost = 100, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 8, rank = 2, base_cost = 200, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 14, rank = 3, base_cost = 900, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 20, rank = 4, base_cost = 2000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 26, rank = 5, base_cost = 5000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 32, rank = 6, base_cost = 10000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 38, rank = 7, base_cost = 14000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 44, rank = 8, base_cost = 23000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 50, rank = 9, base_cost = 32000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 56, rank = 10, base_cost = 38000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },
    { name = "Frostbolt", level = 60, rank = 11, base_cost = 42000, icon = "Spell_Frost_FrostBolt02", source = "trainer" },

    -- Ice Armor
    { name = "Ice Armor", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Frost_ChillingArmor", source = "trainer" },
    { name = "Ice Armor", level = 40, rank = 2, base_cost = 15000, icon = "Spell_Frost_ChillingArmor", source = "trainer" },
    { name = "Ice Armor", level = 50, rank = 3, base_cost = 32000, icon = "Spell_Frost_ChillingArmor", source = "trainer" },
    { name = "Ice Armor", level = 60, rank = 4, base_cost = 42000, icon = "Spell_Frost_ChillingArmor", source = "trainer" },

    -- Ice Barrier (Frost 31-point talent)
    { name = "Ice Barrier", level = 40, rank = 1, base_cost = 0, icon = "Spell_Ice_Lament", source = "talent" },
    { name = "Ice Barrier", level = 46, rank = 2, base_cost = 1170, icon = "Spell_Ice_Lament", source = "talent" },
    { name = "Ice Barrier", level = 52, rank = 3, base_cost = 1750, icon = "Spell_Ice_Lament", source = "talent" },
    { name = "Ice Barrier", level = 58, rank = 4, base_cost = 2000, icon = "Spell_Ice_Lament", source = "talent" },

    -- Ice Block (Frost 21-point talent)
    { name = "Ice Block", level = 30, rank = 1, base_cost = 0, icon = "Spell_Frost_Frost", source = "talent" },

    -- Mage Armor
    { name = "Mage Armor", level = 34, rank = 1, base_cost = 13000, icon = "Spell_MageArmor", source = "trainer" },
    { name = "Mage Armor", level = 46, rank = 2, base_cost = 28000, icon = "Spell_MageArmor", source = "trainer" },
    { name = "Mage Armor", level = 58, rank = 3, base_cost = 40000, icon = "Spell_MageArmor", source = "trainer" },

    -- Mana Shield
    { name = "Mana Shield", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Shadow_DetectLesserInvisibility", source = "trainer" },
    { name = "Mana Shield", level = 28, rank = 2, base_cost = 7000, icon = "Spell_Shadow_DetectLesserInvisibility", source = "trainer" },
    { name = "Mana Shield", level = 36, rank = 3, base_cost = 13000, icon = "Spell_Shadow_DetectLesserInvisibility", source = "trainer" },
    { name = "Mana Shield", level = 44, rank = 4, base_cost = 23000, icon = "Spell_Shadow_DetectLesserInvisibility", source = "trainer" },
    { name = "Mana Shield", level = 52, rank = 5, base_cost = 35000, icon = "Spell_Shadow_DetectLesserInvisibility", source = "trainer" },
    { name = "Mana Shield", level = 60, rank = 6, base_cost = 42000, icon = "Spell_Shadow_DetectLesserInvisibility", source = "trainer" },

    -- Polymorph
    { name = "Polymorph", level = 8, rank = 1, base_cost = 200, icon = "Spell_Nature_Polymorph", source = "trainer" },
    { name = "Polymorph", level = 20, rank = 2, base_cost = 2000, icon = "Spell_Nature_Polymorph", source = "trainer" },
    { name = "Polymorph", level = 40, rank = 3, base_cost = 15000, icon = "Spell_Nature_Polymorph", source = "trainer" },
    { name = "Polymorph", level = 60, rank = 4, base_cost = 42000, icon = "Spell_Nature_Polymorph", source = "trainer" },

    -- Polymorph: Pig (quest)
    { name = "Polymorph: Pig", level = 60, rank = 1, base_cost = 0, icon = "Spell_Magic_PolymorphPig", source = "quest" },

    -- Polymorph: Turtle (book)
    { name = "Polymorph: Turtle", level = 60, rank = 1, base_cost = 0, icon = "Ability_Hunter_Pet_Turtle", source = "book" },

    -- Portal: Darnassus (Alliance)
    { name = "Portal: Darnassus", level = 50, rank = 1, base_cost = 32000, icon = "Spell_Arcane_PortalDarnassus", source = "trainer", faction = "Alliance" },

    -- Portal: Ironforge (Alliance)
    { name = "Portal: Ironforge", level = 50, rank = 1, base_cost = 32000, icon = "Spell_Arcane_PortalIronforge", source = "trainer", faction = "Alliance" },

    -- Portal: Orgrimmar (Horde)
    { name = "Portal: Orgrimmar", level = 50, rank = 1, base_cost = 32000, icon = "Spell_Arcane_PortalOrgrimmar", source = "trainer", faction = "Horde" },

    -- Portal: Stormwind (Alliance)
    { name = "Portal: Stormwind", level = 50, rank = 1, base_cost = 32000, icon = "Spell_Arcane_PortalStormWind", source = "trainer", faction = "Alliance" },

    -- Portal: Thunder Bluff (Horde)
    { name = "Portal: Thunder Bluff", level = 50, rank = 1, base_cost = 32000, icon = "Spell_Arcane_PortalThunderBluff", source = "trainer", faction = "Horde" },

    -- Portal: Undercity (Horde)
    { name = "Portal: Undercity", level = 50, rank = 1, base_cost = 32000, icon = "Spell_Arcane_PortalUnderCity", source = "trainer", faction = "Horde" },

    -- Presence of Mind (Arcane 21-point talent)
    { name = "Presence of Mind", level = 30, rank = 1, base_cost = 0, icon = "Spell_Nature_EnchantArmor", source = "talent" },

    -- Pyroblast (Fire 11-point talent)
    { name = "Pyroblast", level = 20, rank = 1, base_cost = 0, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 24, rank = 2, base_cost = 200, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 30, rank = 3, base_cost = 400, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 36, rank = 4, base_cost = 650, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 42, rank = 5, base_cost = 900, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 48, rank = 6, base_cost = 1400, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 54, rank = 7, base_cost = 1800, icon = "Spell_Fire_Fireball02", source = "talent" },
    { name = "Pyroblast", level = 60, rank = 8, base_cost = 1890, icon = "Spell_Fire_Fireball02", source = "talent" },

    -- Remove Lesser Curse
    { name = "Remove Lesser Curse", level = 18, rank = 1, base_cost = 1800, icon = "Spell_Nature_RemoveCurse", source = "trainer" },

    -- Scorch
    { name = "Scorch", level = 22, rank = 1, base_cost = 3000, icon = "Spell_Fire_SoulBurn", source = "trainer" },
    { name = "Scorch", level = 28, rank = 2, base_cost = 7000, icon = "Spell_Fire_SoulBurn", source = "trainer" },
    { name = "Scorch", level = 34, rank = 3, base_cost = 12000, icon = "Spell_Fire_SoulBurn", source = "trainer" },
    { name = "Scorch", level = 40, rank = 4, base_cost = 15000, icon = "Spell_Fire_SoulBurn", source = "trainer" },
    { name = "Scorch", level = 46, rank = 5, base_cost = 26000, icon = "Spell_Fire_SoulBurn", source = "trainer" },
    { name = "Scorch", level = 52, rank = 6, base_cost = 35000, icon = "Spell_Fire_SoulBurn", source = "trainer" },
    { name = "Scorch", level = 58, rank = 7, base_cost = 40000, icon = "Spell_Fire_SoulBurn", source = "trainer" },

    -- Slow Fall
    { name = "Slow Fall", level = 12, rank = 1, base_cost = 600, icon = "Spell_Magic_FeatherFall", source = "trainer" },

    -- Teleport: Darnassus (Alliance)
    { name = "Teleport: Darnassus", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Arcane_TeleportDarnassus", source = "trainer", faction = "Alliance" },

    -- Teleport: Ironforge (Alliance)
    { name = "Teleport: Ironforge", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Arcane_TeleportIronforge", source = "trainer", faction = "Alliance" },

    -- Teleport: Orgrimmar (Horde)
    { name = "Teleport: Orgrimmar", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Arcane_TeleportOrgrimmar", source = "trainer", faction = "Horde" },

    -- Teleport: Stormwind (Alliance)
    { name = "Teleport: Stormwind", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Arcane_TeleportStormWind", source = "trainer", faction = "Alliance" },

    -- Teleport: Thunder Bluff (Horde)
    { name = "Teleport: Thunder Bluff", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Arcane_TeleportThunderBluff", source = "trainer", faction = "Horde" },

    -- Teleport: Undercity (Horde)
    { name = "Teleport: Undercity", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Arcane_TeleportUnderCity", source = "trainer", faction = "Horde" },
}