-- TODO: Generated by Opus 4.5 and not yet verified

local Deathless = Deathless

Deathless.Data = Deathless.Data or {}
Deathless.Data.Abilities = Deathless.Data.Abilities or {}

-- base_cost is stored in copper (1 silver = 100 copper, 1 gold = 10000 copper)
-- Actual cost may be reduced by reputation discounts (5% honored, 10% revered, 15% exalted)
-- Source types:
--   trainer - Learned from class trainer
--   talent  - Requires talent points (only shown if base talent is learned)
--   class   - Innate class ability (learned automatically)
--   book    - Learned from a drop/item (codex)
--   quest   - Learned from completing a quest (includes racial abilities)
-- Sorted alphabetically by name, then by rank
-- Racial priest abilities are obtained via quests at level 10 and 20
-- See https://www.wowhead.com/classic/spells/abilities/priest for source data
Deathless.Data.Abilities["Priest"] = {
    -- Abolish Disease
    { name = "Abolish Disease", level = 32, rank = 1, base_cost = 10000, icon = "Spell_Nature_NullifyDisease", source = "trainer" },

    -- Cure Disease
    { name = "Cure Disease", level = 14, rank = 1, base_cost = 900, icon = "Spell_Holy_NullifyDisease", source = "trainer" },

    -- Desperate Prayer (Dwarf/Human racial - quest)
    { name = "Desperate Prayer", level = 10, rank = 1, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },
    { name = "Desperate Prayer", level = 18, rank = 2, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },
    { name = "Desperate Prayer", level = 26, rank = 3, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },
    { name = "Desperate Prayer", level = 34, rank = 4, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },
    { name = "Desperate Prayer", level = 42, rank = 5, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },
    { name = "Desperate Prayer", level = 50, rank = 6, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },
    { name = "Desperate Prayer", level = 58, rank = 7, base_cost = 0, icon = "Spell_Holy_Restoration", source = "quest" },

    -- Devouring Plague (Undead racial - quest)
    { name = "Devouring Plague", level = 20, rank = 1, base_cost = 0, icon = "Spell_Shadow_DevouringPlague", source = "quest" },
    { name = "Devouring Plague", level = 28, rank = 2, base_cost = 0, icon = "Spell_Shadow_DevouringPlague", source = "quest" },
    { name = "Devouring Plague", level = 36, rank = 3, base_cost = 0, icon = "Spell_Shadow_DevouringPlague", source = "quest" },
    { name = "Devouring Plague", level = 44, rank = 4, base_cost = 0, icon = "Spell_Shadow_DevouringPlague", source = "quest" },
    { name = "Devouring Plague", level = 52, rank = 5, base_cost = 0, icon = "Spell_Shadow_DevouringPlague", source = "quest" },
    { name = "Devouring Plague", level = 60, rank = 6, base_cost = 0, icon = "Spell_Shadow_DevouringPlague", source = "quest" },

    -- Divine Spirit (Discipline talent)
    { name = "Divine Spirit", level = 30, rank = 1, base_cost = 0, icon = "Spell_Holy_DivineSpirit", source = "talent" },
    { name = "Divine Spirit", level = 40, rank = 2, base_cost = 15000, icon = "Spell_Holy_DivineSpirit", source = "talent" },
    { name = "Divine Spirit", level = 50, rank = 3, base_cost = 32000, icon = "Spell_Holy_DivineSpirit", source = "talent" },
    { name = "Divine Spirit", level = 60, rank = 4, base_cost = 42000, icon = "Spell_Holy_DivineSpirit", source = "talent" },

    -- Dispel Magic
    { name = "Dispel Magic", level = 18, rank = 1, base_cost = 1800, icon = "Spell_Holy_DispelMagic", source = "trainer" },
    { name = "Dispel Magic", level = 36, rank = 2, base_cost = 13000, icon = "Spell_Holy_DispelMagic", source = "trainer" },

    -- Elune's Grace (Night Elf racial - quest)
    { name = "Elune's Grace", level = 20, rank = 1, base_cost = 0, icon = "Spell_Holy_ElunesGrace", source = "quest" },
    { name = "Elune's Grace", level = 28, rank = 2, base_cost = 0, icon = "Spell_Holy_ElunesGrace", source = "quest" },
    { name = "Elune's Grace", level = 36, rank = 3, base_cost = 0, icon = "Spell_Holy_ElunesGrace", source = "quest" },
    { name = "Elune's Grace", level = 44, rank = 4, base_cost = 0, icon = "Spell_Holy_ElunesGrace", source = "quest" },
    { name = "Elune's Grace", level = 52, rank = 5, base_cost = 0, icon = "Spell_Holy_ElunesGrace", source = "quest" },
    { name = "Elune's Grace", level = 60, rank = 6, base_cost = 0, icon = "Spell_Holy_ElunesGrace", source = "quest" },

    -- Fade
    { name = "Fade", level = 8, rank = 1, base_cost = 200, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },
    { name = "Fade", level = 16, rank = 2, base_cost = 1500, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },
    { name = "Fade", level = 24, rank = 3, base_cost = 4000, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },
    { name = "Fade", level = 32, rank = 4, base_cost = 10000, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },
    { name = "Fade", level = 40, rank = 5, base_cost = 15000, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },
    { name = "Fade", level = 48, rank = 6, base_cost = 28000, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },
    { name = "Fade", level = 56, rank = 7, base_cost = 38000, icon = "Spell_Magic_LesserInvisibilty", source = "trainer" },

    -- Fear Ward (Dwarf racial - quest)
    { name = "Fear Ward", level = 20, rank = 1, base_cost = 0, icon = "Spell_Holy_Excorcism", source = "quest" },

    -- Feedback (Human racial - quest)
    { name = "Feedback", level = 20, rank = 1, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "quest" },
    { name = "Feedback", level = 28, rank = 2, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "quest" },
    { name = "Feedback", level = 36, rank = 3, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "quest" },
    { name = "Feedback", level = 44, rank = 4, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "quest" },
    { name = "Feedback", level = 52, rank = 5, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "quest" },
    { name = "Feedback", level = 60, rank = 6, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "quest" },

    -- Flash Heal
    { name = "Flash Heal", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Flash Heal", level = 26, rank = 2, base_cost = 5000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Flash Heal", level = 32, rank = 3, base_cost = 10000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Flash Heal", level = 38, rank = 4, base_cost = 14000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Flash Heal", level = 44, rank = 5, base_cost = 23000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Flash Heal", level = 50, rank = 6, base_cost = 32000, icon = "Spell_Holy_FlashHeal", source = "trainer" },
    { name = "Flash Heal", level = 56, rank = 7, base_cost = 38000, icon = "Spell_Holy_FlashHeal", source = "trainer" },

    -- Greater Heal
    { name = "Greater Heal", level = 40, rank = 1, base_cost = 15000, icon = "Spell_Holy_GreaterHeal", source = "trainer" },
    { name = "Greater Heal", level = 46, rank = 2, base_cost = 26000, icon = "Spell_Holy_GreaterHeal", source = "trainer" },
    { name = "Greater Heal", level = 52, rank = 3, base_cost = 35000, icon = "Spell_Holy_GreaterHeal", source = "trainer" },
    { name = "Greater Heal", level = 58, rank = 4, base_cost = 40000, icon = "Spell_Holy_GreaterHeal", source = "trainer" },
    { name = "Greater Heal", level = 60, rank = 5, base_cost = 0, icon = "Spell_Holy_GreaterHeal", source = "book" },

    -- Heal
    { name = "Heal", level = 16, rank = 1, base_cost = 1500, icon = "Spell_Holy_Heal", source = "trainer" },
    { name = "Heal", level = 22, rank = 2, base_cost = 3000, icon = "Spell_Holy_Heal", source = "trainer" },
    { name = "Heal", level = 28, rank = 3, base_cost = 7000, icon = "Spell_Holy_Heal", source = "trainer" },
    { name = "Heal", level = 34, rank = 4, base_cost = 12000, icon = "Spell_Holy_Heal", source = "trainer" },

    -- Hex of Weakness (Troll racial - quest)
    { name = "Hex of Weakness", level = 10, rank = 1, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },
    { name = "Hex of Weakness", level = 18, rank = 2, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },
    { name = "Hex of Weakness", level = 26, rank = 3, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },
    { name = "Hex of Weakness", level = 34, rank = 4, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },
    { name = "Hex of Weakness", level = 42, rank = 5, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },
    { name = "Hex of Weakness", level = 50, rank = 6, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },
    { name = "Hex of Weakness", level = 58, rank = 7, base_cost = 0, icon = "Spell_Shadow_FingerOfDeath", source = "quest" },

    -- Holy Fire
    { name = "Holy Fire", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 24, rank = 2, base_cost = 4000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 30, rank = 3, base_cost = 8000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 36, rank = 4, base_cost = 13000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 42, rank = 5, base_cost = 18000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 48, rank = 6, base_cost = 28000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 54, rank = 7, base_cost = 36000, icon = "Spell_Holy_SearingLight", source = "trainer" },
    { name = "Holy Fire", level = 60, rank = 8, base_cost = 42000, icon = "Spell_Holy_SearingLight", source = "trainer" },

    -- Holy Nova (trainer in Classic, was talent earlier)
    { name = "Holy Nova", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Holy_HolyNova", source = "trainer" },
    { name = "Holy Nova", level = 28, rank = 2, base_cost = 7000, icon = "Spell_Holy_HolyNova", source = "trainer" },
    { name = "Holy Nova", level = 36, rank = 3, base_cost = 13000, icon = "Spell_Holy_HolyNova", source = "trainer" },
    { name = "Holy Nova", level = 44, rank = 4, base_cost = 23000, icon = "Spell_Holy_HolyNova", source = "trainer" },
    { name = "Holy Nova", level = 52, rank = 5, base_cost = 35000, icon = "Spell_Holy_HolyNova", source = "trainer" },
    { name = "Holy Nova", level = 60, rank = 6, base_cost = 42000, icon = "Spell_Holy_HolyNova", source = "trainer" },

    -- Inner Fire
    { name = "Inner Fire", level = 12, rank = 1, base_cost = 600, icon = "Spell_Holy_InnerFire", source = "trainer" },
    { name = "Inner Fire", level = 20, rank = 2, base_cost = 2000, icon = "Spell_Holy_InnerFire", source = "trainer" },
    { name = "Inner Fire", level = 30, rank = 3, base_cost = 8000, icon = "Spell_Holy_InnerFire", source = "trainer" },
    { name = "Inner Fire", level = 40, rank = 4, base_cost = 15000, icon = "Spell_Holy_InnerFire", source = "trainer" },
    { name = "Inner Fire", level = 50, rank = 5, base_cost = 32000, icon = "Spell_Holy_InnerFire", source = "trainer" },
    { name = "Inner Fire", level = 60, rank = 6, base_cost = 42000, icon = "Spell_Holy_InnerFire", source = "trainer" },

    -- Inner Focus (Discipline talent)
    { name = "Inner Focus", level = 20, rank = 1, base_cost = 0, icon = "Spell_Frost_WindWalkOn", source = "talent" },

    -- Lesser Heal (innate)
    { name = "Lesser Heal", level = 1, rank = 1, base_cost = 0, icon = "Spell_Holy_LesserHeal", source = "class" },
    { name = "Lesser Heal", level = 4, rank = 2, base_cost = 100, icon = "Spell_Holy_LesserHeal", source = "trainer" },
    { name = "Lesser Heal", level = 10, rank = 3, base_cost = 400, icon = "Spell_Holy_LesserHeal", source = "trainer" },

    -- Levitate
    { name = "Levitate", level = 34, rank = 1, base_cost = 12000, icon = "Spell_Holy_LayOnHands", source = "trainer" },

    -- Lightwell (Holy talent)
    { name = "Lightwell", level = 40, rank = 1, base_cost = 0, icon = "Spell_Holy_SummonLightwell", source = "talent" },
    { name = "Lightwell", level = 50, rank = 2, base_cost = 16000, icon = "Spell_Holy_SummonLightwell", source = "talent" },
    { name = "Lightwell", level = 60, rank = 3, base_cost = 21000, icon = "Spell_Holy_SummonLightwell", source = "talent" },

    -- Mana Burn
    { name = "Mana Burn", level = 24, rank = 1, base_cost = 4000, icon = "Spell_Shadow_ManaBurn", source = "trainer" },
    { name = "Mana Burn", level = 32, rank = 2, base_cost = 10000, icon = "Spell_Shadow_ManaBurn", source = "trainer" },
    { name = "Mana Burn", level = 40, rank = 3, base_cost = 15000, icon = "Spell_Shadow_ManaBurn", source = "trainer" },
    { name = "Mana Burn", level = 48, rank = 4, base_cost = 28000, icon = "Spell_Shadow_ManaBurn", source = "trainer" },
    { name = "Mana Burn", level = 56, rank = 5, base_cost = 38000, icon = "Spell_Shadow_ManaBurn", source = "trainer" },

    -- Mind Blast
    { name = "Mind Blast", level = 10, rank = 1, base_cost = 400, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 16, rank = 2, base_cost = 1500, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 22, rank = 3, base_cost = 3000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 28, rank = 4, base_cost = 7000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 34, rank = 5, base_cost = 12000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 40, rank = 6, base_cost = 15000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 46, rank = 7, base_cost = 26000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 52, rank = 8, base_cost = 35000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },
    { name = "Mind Blast", level = 58, rank = 9, base_cost = 40000, icon = "Spell_Shadow_UnholyFrenzy", source = "trainer" },

    -- Mind Control
    { name = "Mind Control", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Shadow_ShadowWordDominate", source = "trainer" },
    { name = "Mind Control", level = 44, rank = 2, base_cost = 23000, icon = "Spell_Shadow_ShadowWordDominate", source = "trainer" },
    { name = "Mind Control", level = 58, rank = 3, base_cost = 40000, icon = "Spell_Shadow_ShadowWordDominate", source = "trainer" },

    -- Mind Flay (Shadow talent)
    { name = "Mind Flay", level = 20, rank = 1, base_cost = 0, icon = "Spell_Shadow_SiphonMana", source = "talent" },
    { name = "Mind Flay", level = 28, rank = 2, base_cost = 3500, icon = "Spell_Shadow_SiphonMana", source = "talent" },
    { name = "Mind Flay", level = 36, rank = 3, base_cost = 6500, icon = "Spell_Shadow_SiphonMana", source = "talent" },
    { name = "Mind Flay", level = 44, rank = 4, base_cost = 11500, icon = "Spell_Shadow_SiphonMana", source = "talent" },
    { name = "Mind Flay", level = 52, rank = 5, base_cost = 17500, icon = "Spell_Shadow_SiphonMana", source = "talent" },
    { name = "Mind Flay", level = 60, rank = 6, base_cost = 21000, icon = "Spell_Shadow_SiphonMana", source = "talent" },

    -- Mind Soothe
    { name = "Mind Soothe", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Holy_MindSooth", source = "trainer" },
    { name = "Mind Soothe", level = 28, rank = 2, base_cost = 7000, icon = "Spell_Holy_MindSooth", source = "trainer" },
    { name = "Mind Soothe", level = 36, rank = 3, base_cost = 13000, icon = "Spell_Holy_MindSooth", source = "trainer" },
    { name = "Mind Soothe", level = 44, rank = 4, base_cost = 23000, icon = "Spell_Holy_MindSooth", source = "trainer" },

    -- Mind Vision
    { name = "Mind Vision", level = 22, rank = 1, base_cost = 3000, icon = "Spell_Holy_MindVision", source = "trainer" },
    { name = "Mind Vision", level = 52, rank = 2, base_cost = 35000, icon = "Spell_Holy_MindVision", source = "trainer" },

    -- Power Infusion (Discipline 31-point talent)
    { name = "Power Infusion", level = 40, rank = 1, base_cost = 0, icon = "Spell_Holy_PowerInfusion", source = "talent" },

    -- Power Word: Fortitude (innate)
    { name = "Power Word: Fortitude", level = 1, rank = 1, base_cost = 0, icon = "Spell_Holy_WordFortitude", source = "class" },
    { name = "Power Word: Fortitude", level = 12, rank = 2, base_cost = 600, icon = "Spell_Holy_WordFortitude", source = "trainer" },
    { name = "Power Word: Fortitude", level = 24, rank = 3, base_cost = 4000, icon = "Spell_Holy_WordFortitude", source = "trainer" },
    { name = "Power Word: Fortitude", level = 36, rank = 4, base_cost = 13000, icon = "Spell_Holy_WordFortitude", source = "trainer" },
    { name = "Power Word: Fortitude", level = 48, rank = 5, base_cost = 28000, icon = "Spell_Holy_WordFortitude", source = "trainer" },
    { name = "Power Word: Fortitude", level = 60, rank = 6, base_cost = 42000, icon = "Spell_Holy_WordFortitude", source = "trainer" },

    -- Power Word: Shield
    { name = "Power Word: Shield", level = 6, rank = 1, base_cost = 100, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 12, rank = 2, base_cost = 600, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 18, rank = 3, base_cost = 1800, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 24, rank = 4, base_cost = 4000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 30, rank = 5, base_cost = 8000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 36, rank = 6, base_cost = 13000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 42, rank = 7, base_cost = 18000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 48, rank = 8, base_cost = 28000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 54, rank = 9, base_cost = 36000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },
    { name = "Power Word: Shield", level = 60, rank = 10, base_cost = 42000, icon = "Spell_Holy_PowerWordShield", source = "trainer" },

    -- Prayer of Fortitude (book for R1)
    { name = "Prayer of Fortitude", level = 48, rank = 1, base_cost = 0, icon = "Spell_Holy_PrayerOfFortitude", source = "book" },
    { name = "Prayer of Fortitude", level = 60, rank = 2, base_cost = 0, icon = "Spell_Holy_PrayerOfFortitude", source = "book" },

    -- Prayer of Healing
    { name = "Prayer of Healing", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Holy_PrayerOfHealing02", source = "trainer" },
    { name = "Prayer of Healing", level = 40, rank = 2, base_cost = 15000, icon = "Spell_Holy_PrayerOfHealing02", source = "trainer" },
    { name = "Prayer of Healing", level = 50, rank = 3, base_cost = 32000, icon = "Spell_Holy_PrayerOfHealing02", source = "trainer" },
    { name = "Prayer of Healing", level = 60, rank = 4, base_cost = 42000, icon = "Spell_Holy_PrayerOfHealing02", source = "trainer" },
    { name = "Prayer of Healing", level = 60, rank = 5, base_cost = 0, icon = "Spell_Holy_PrayerOfHealing02", source = "book" },

    -- Prayer of Shadow Protection (book)
    { name = "Prayer of Shadow Protection", level = 56, rank = 1, base_cost = 0, icon = "Spell_Holy_PrayerOfShadowProtection", source = "book" },

    -- Prayer of Spirit (book)
    { name = "Prayer of Spirit", level = 60, rank = 1, base_cost = 0, icon = "Spell_Holy_PrayerOfSpirit", source = "book" },

    -- Psychic Scream
    { name = "Psychic Scream", level = 14, rank = 1, base_cost = 900, icon = "Spell_Shadow_PsychicScream", source = "trainer" },
    { name = "Psychic Scream", level = 28, rank = 2, base_cost = 7000, icon = "Spell_Shadow_PsychicScream", source = "trainer" },
    { name = "Psychic Scream", level = 42, rank = 3, base_cost = 18000, icon = "Spell_Shadow_PsychicScream", source = "trainer" },
    { name = "Psychic Scream", level = 56, rank = 4, base_cost = 38000, icon = "Spell_Shadow_PsychicScream", source = "trainer" },

    -- Renew
    { name = "Renew", level = 8, rank = 1, base_cost = 200, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 14, rank = 2, base_cost = 900, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 20, rank = 3, base_cost = 2000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 26, rank = 4, base_cost = 5000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 32, rank = 5, base_cost = 10000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 38, rank = 6, base_cost = 14000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 44, rank = 7, base_cost = 23000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 50, rank = 8, base_cost = 32000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 56, rank = 9, base_cost = 38000, icon = "Spell_Holy_Renew", source = "trainer" },
    { name = "Renew", level = 60, rank = 10, base_cost = 0, icon = "Spell_Holy_Renew", source = "book" },

    -- Resurrection
    { name = "Resurrection", level = 10, rank = 1, base_cost = 400, icon = "Spell_Holy_Resurrection", source = "trainer" },
    { name = "Resurrection", level = 22, rank = 2, base_cost = 3000, icon = "Spell_Holy_Resurrection", source = "trainer" },
    { name = "Resurrection", level = 34, rank = 3, base_cost = 12000, icon = "Spell_Holy_Resurrection", source = "trainer" },
    { name = "Resurrection", level = 46, rank = 4, base_cost = 26000, icon = "Spell_Holy_Resurrection", source = "trainer" },
    { name = "Resurrection", level = 58, rank = 5, base_cost = 40000, icon = "Spell_Holy_Resurrection", source = "trainer" },

    -- Shackle Undead
    { name = "Shackle Undead", level = 20, rank = 1, base_cost = 2000, icon = "Spell_Nature_Slow", source = "trainer" },
    { name = "Shackle Undead", level = 40, rank = 2, base_cost = 15000, icon = "Spell_Nature_Slow", source = "trainer" },
    { name = "Shackle Undead", level = 60, rank = 3, base_cost = 42000, icon = "Spell_Nature_Slow", source = "trainer" },

    -- Shadow Protection
    { name = "Shadow Protection", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Shadow_AntiShadow", source = "trainer" },
    { name = "Shadow Protection", level = 42, rank = 2, base_cost = 18000, icon = "Spell_Shadow_AntiShadow", source = "trainer" },
    { name = "Shadow Protection", level = 56, rank = 3, base_cost = 38000, icon = "Spell_Shadow_AntiShadow", source = "trainer" },

    -- Shadow Word: Pain (innate)
    { name = "Shadow Word: Pain", level = 4, rank = 1, base_cost = 100, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 10, rank = 2, base_cost = 400, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 18, rank = 3, base_cost = 1800, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 26, rank = 4, base_cost = 5000, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 34, rank = 5, base_cost = 12000, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 42, rank = 6, base_cost = 18000, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 50, rank = 7, base_cost = 32000, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },
    { name = "Shadow Word: Pain", level = 58, rank = 8, base_cost = 40000, icon = "Spell_Shadow_ShadowWordPain", source = "trainer" },

    -- Shadowform (Shadow 31-point talent)
    { name = "Shadowform", level = 40, rank = 1, base_cost = 0, icon = "Spell_Shadow_Shadowform", source = "talent" },

    -- Shadowguard (Troll racial - quest)
    { name = "Shadowguard", level = 20, rank = 1, base_cost = 0, icon = "Spell_Nature_LightningShield", source = "quest" },
    { name = "Shadowguard", level = 28, rank = 2, base_cost = 0, icon = "Spell_Nature_LightningShield", source = "quest" },
    { name = "Shadowguard", level = 36, rank = 3, base_cost = 0, icon = "Spell_Nature_LightningShield", source = "quest" },
    { name = "Shadowguard", level = 44, rank = 4, base_cost = 0, icon = "Spell_Nature_LightningShield", source = "quest" },
    { name = "Shadowguard", level = 52, rank = 5, base_cost = 0, icon = "Spell_Nature_LightningShield", source = "quest" },
    { name = "Shadowguard", level = 60, rank = 6, base_cost = 0, icon = "Spell_Nature_LightningShield", source = "quest" },

    -- Silence (Shadow talent)
    { name = "Silence", level = 30, rank = 1, base_cost = 0, icon = "Spell_Shadow_ImpPhaseShift", source = "talent" },

    -- Smite (innate)
    { name = "Smite", level = 1, rank = 1, base_cost = 0, icon = "Spell_Holy_HolySmite", source = "class" },
    { name = "Smite", level = 6, rank = 2, base_cost = 100, icon = "Spell_Holy_HolySmite", source = "trainer" },
    { name = "Smite", level = 14, rank = 3, base_cost = 900, icon = "Spell_Holy_HolySmite", source = "trainer" },
    { name = "Smite", level = 22, rank = 4, base_cost = 3000, icon = "Spell_Holy_HolySmite", source = "trainer" },
    { name = "Smite", level = 30, rank = 5, base_cost = 8000, icon = "Spell_Holy_HolySmite", source = "trainer" },
    { name = "Smite", level = 38, rank = 6, base_cost = 14000, icon = "Spell_Holy_HolySmite", source = "trainer" },
    { name = "Smite", level = 46, rank = 7, base_cost = 26000, icon = "Spell_Holy_HolySmite", source = "trainer" },
    { name = "Smite", level = 54, rank = 8, base_cost = 36000, icon = "Spell_Holy_HolySmite", source = "trainer" },

    -- Starshards (Night Elf racial - quest)
    { name = "Starshards", level = 10, rank = 1, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },
    { name = "Starshards", level = 18, rank = 2, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },
    { name = "Starshards", level = 26, rank = 3, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },
    { name = "Starshards", level = 34, rank = 4, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },
    { name = "Starshards", level = 42, rank = 5, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },
    { name = "Starshards", level = 50, rank = 6, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },
    { name = "Starshards", level = 58, rank = 7, base_cost = 0, icon = "Spell_Arcane_Starfire", source = "quest" },

    -- Touch of Weakness (Undead racial - quest)
    { name = "Touch of Weakness", level = 10, rank = 1, base_cost = 0, icon = "Spell_Shadow_DeadofNight", source = "quest" },
    { name = "Touch of Weakness", level = 20, rank = 2, base_cost = 0, icon = "Spell_Shadow_DeadofNight", source = "quest" },
    { name = "Touch of Weakness", level = 30, rank = 3, base_cost = 0, icon = "Spell_Shadow_DeadofNight", source = "quest" },
    { name = "Touch of Weakness", level = 40, rank = 4, base_cost = 0, icon = "Spell_Shadow_DeadofNight", source = "quest" },
    { name = "Touch of Weakness", level = 50, rank = 5, base_cost = 0, icon = "Spell_Shadow_DeadofNight", source = "quest" },
    { name = "Touch of Weakness", level = 60, rank = 6, base_cost = 0, icon = "Spell_Shadow_DeadofNight", source = "quest" },

    -- Vampiric Embrace (Shadow talent)
    { name = "Vampiric Embrace", level = 30, rank = 1, base_cost = 0, icon = "Spell_Shadow_UnsummonBuilding", source = "talent" },
}