-- TODO: Generated by Opus 4.5 and not yet verified

local Deathless = Deathless

Deathless.Data = Deathless.Data or {}
Deathless.Data.Abilities = Deathless.Data.Abilities or {}

-- base_cost is stored in copper (1 silver = 100 copper, 1 gold = 10000 copper)
-- Actual cost may be reduced by reputation discounts (5% honored, 10% revered, 15% exalted)
-- Source types:
--   trainer - Learned from class trainer
--   talent  - Requires talent points (only shown if base talent is learned)
--   class   - Innate class ability (learned automatically)
--   book    - Learned from a drop/item
--   quest   - Learned from completing a quest
-- Sorted alphabetically by name, then by rank
-- Poisons are crafting recipes, not combat abilities - included separately
-- See https://www.wowhead.com/classic/spells/abilities/rogue for source data
Deathless.Data.Abilities["Rogue"] = {
    -- Adrenaline Rush (Combat 31-point talent)
    { name = "Adrenaline Rush", level = 40, rank = 1, base_cost = 0, icon = "Spell_Shadow_ShadowWordDominate", source = "talent" },

    -- Ambush
    { name = "Ambush", level = 18, rank = 1, base_cost = 1800, icon = "Ability_Rogue_Ambush", source = "trainer" },
    { name = "Ambush", level = 26, rank = 2, base_cost = 5000, icon = "Ability_Rogue_Ambush", source = "trainer" },
    { name = "Ambush", level = 34, rank = 3, base_cost = 12000, icon = "Ability_Rogue_Ambush", source = "trainer" },
    { name = "Ambush", level = 42, rank = 4, base_cost = 18000, icon = "Ability_Rogue_Ambush", source = "trainer" },
    { name = "Ambush", level = 50, rank = 5, base_cost = 32000, icon = "Ability_Rogue_Ambush", source = "trainer" },
    { name = "Ambush", level = 58, rank = 6, base_cost = 40000, icon = "Ability_Rogue_Ambush", source = "trainer" },

    -- Backstab
    { name = "Backstab", level = 4, rank = 1, base_cost = 100, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 12, rank = 2, base_cost = 600, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 20, rank = 3, base_cost = 2000, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 28, rank = 4, base_cost = 7000, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 36, rank = 5, base_cost = 13000, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 44, rank = 6, base_cost = 23000, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 52, rank = 7, base_cost = 35000, icon = "Ability_BackStab", source = "trainer" },
    { name = "Backstab", level = 60, rank = 8, base_cost = 42000, icon = "Ability_BackStab", source = "trainer" },

    -- Blade Flurry (Combat 21-point talent)
    { name = "Blade Flurry", level = 30, rank = 1, base_cost = 0, icon = "Ability_Warrior_PunishingBlow", source = "talent" },

    -- Blind
    { name = "Blind", level = 34, rank = 1, base_cost = 12000, icon = "Spell_Shadow_MindSteal", source = "trainer" },

    -- Cheap Shot
    { name = "Cheap Shot", level = 26, rank = 1, base_cost = 5000, icon = "Ability_CheapShot", source = "trainer" },

    -- Cold Blood (Assassination 21-point talent)
    { name = "Cold Blood", level = 30, rank = 1, base_cost = 0, icon = "Spell_Ice_Lament", source = "talent" },

    -- Crippling Poison
    { name = "Crippling Poison", level = 20, rank = 1, base_cost = 2000, icon = "Ability_PoisonSting", source = "trainer" },
    { name = "Crippling Poison", level = 50, rank = 2, base_cost = 32000, icon = "Ability_PoisonSting", source = "trainer" },

    -- Deadly Poison
    { name = "Deadly Poison", level = 30, rank = 1, base_cost = 8000, icon = "Ability_Rogue_DualWeild", source = "trainer" },
    { name = "Deadly Poison", level = 38, rank = 2, base_cost = 14000, icon = "Ability_Rogue_DualWeild", source = "trainer" },
    { name = "Deadly Poison", level = 46, rank = 3, base_cost = 26000, icon = "Ability_Rogue_DualWeild", source = "trainer" },
    { name = "Deadly Poison", level = 54, rank = 4, base_cost = 36000, icon = "Ability_Rogue_DualWeild", source = "trainer" },
    { name = "Deadly Poison", level = 60, rank = 5, base_cost = 0, icon = "Ability_Rogue_DualWeild", source = "book" },

    -- Detect Traps
    { name = "Detect Traps", level = 24, rank = 1, base_cost = 4000, icon = "Ability_Spy", source = "trainer" },

    -- Disarm Trap
    { name = "Disarm Trap", level = 30, rank = 1, base_cost = 8000, icon = "Spell_Shadow_GrimWard", source = "trainer" },

    -- Distract
    { name = "Distract", level = 22, rank = 1, base_cost = 3000, icon = "Ability_Rogue_Distract", source = "trainer" },

    -- Dual Wield (passive)
    { name = "Dual Wield", level = 10, rank = 1, base_cost = 0, icon = "Ability_DualWield", source = "trainer" },

    -- Evasion
    { name = "Evasion", level = 8, rank = 1, base_cost = 200, icon = "Spell_Shadow_ShadowWard", source = "trainer" },

    -- Eviscerate (innate)
    { name = "Eviscerate", level = 1, rank = 1, base_cost = 0, icon = "Ability_Rogue_Eviscerate", source = "class" },
    { name = "Eviscerate", level = 8, rank = 2, base_cost = 200, icon = "Ability_Rogue_Eviscerate", source = "trainer" },
    { name = "Eviscerate", level = 16, rank = 3, base_cost = 1500, icon = "Ability_Rogue_Eviscerate", source = "trainer" },
    { name = "Eviscerate", level = 24, rank = 4, base_cost = 4000, icon = "Ability_Rogue_Eviscerate", source = "trainer" },
    { name = "Eviscerate", level = 32, rank = 5, base_cost = 10000, icon = "Ability_Rogue_Eviscerate", source = "trainer" },
    { name = "Eviscerate", level = 40, rank = 6, base_cost = 15000, icon = "Ability_Rogue_Eviscerate", source = "trainer" },
    { name = "Eviscerate", level = 48, rank = 7, base_cost = 28000, icon = "Ability_Rogue_Eviscerate", source = "trainer" },
    { name = "Eviscerate", level = 56, rank = 8, base_cost = 38000, icon = "Ability_Rogue_Eviscerate", source = "trainer" },

    -- Expose Armor
    { name = "Expose Armor", level = 14, rank = 1, base_cost = 900, icon = "Ability_Warrior_Riposte", source = "trainer" },
    { name = "Expose Armor", level = 26, rank = 2, base_cost = 5000, icon = "Ability_Warrior_Riposte", source = "trainer" },
    { name = "Expose Armor", level = 38, rank = 3, base_cost = 14000, icon = "Ability_Warrior_Riposte", source = "trainer" },
    { name = "Expose Armor", level = 50, rank = 4, base_cost = 32000, icon = "Ability_Warrior_Riposte", source = "trainer" },
    { name = "Expose Armor", level = 60, rank = 5, base_cost = 42000, icon = "Ability_Warrior_Riposte", source = "trainer" },

    -- Feint
    { name = "Feint", level = 16, rank = 1, base_cost = 1500, icon = "Ability_Rogue_Feint", source = "trainer" },
    { name = "Feint", level = 28, rank = 2, base_cost = 7000, icon = "Ability_Rogue_Feint", source = "trainer" },
    { name = "Feint", level = 40, rank = 3, base_cost = 15000, icon = "Ability_Rogue_Feint", source = "trainer" },
    { name = "Feint", level = 52, rank = 4, base_cost = 35000, icon = "Ability_Rogue_Feint", source = "trainer" },

    -- Garrote
    { name = "Garrote", level = 14, rank = 1, base_cost = 900, icon = "Ability_Rogue_Garrote", source = "trainer" },
    { name = "Garrote", level = 22, rank = 2, base_cost = 3000, icon = "Ability_Rogue_Garrote", source = "trainer" },
    { name = "Garrote", level = 30, rank = 3, base_cost = 8000, icon = "Ability_Rogue_Garrote", source = "trainer" },
    { name = "Garrote", level = 38, rank = 4, base_cost = 14000, icon = "Ability_Rogue_Garrote", source = "trainer" },
    { name = "Garrote", level = 46, rank = 5, base_cost = 26000, icon = "Ability_Rogue_Garrote", source = "trainer" },
    { name = "Garrote", level = 54, rank = 6, base_cost = 36000, icon = "Ability_Rogue_Garrote", source = "trainer" },

    -- Ghostly Strike (Subtlety 11-point talent)
    { name = "Ghostly Strike", level = 20, rank = 1, base_cost = 0, icon = "Spell_Shadow_Curse", source = "talent" },

    -- Gouge
    { name = "Gouge", level = 6, rank = 1, base_cost = 100, icon = "Ability_Gouge", source = "trainer" },
    { name = "Gouge", level = 18, rank = 2, base_cost = 1800, icon = "Ability_Gouge", source = "trainer" },
    { name = "Gouge", level = 32, rank = 3, base_cost = 10000, icon = "Ability_Gouge", source = "trainer" },
    { name = "Gouge", level = 46, rank = 4, base_cost = 26000, icon = "Ability_Gouge", source = "trainer" },
    { name = "Gouge", level = 60, rank = 5, base_cost = 42000, icon = "Ability_Gouge", source = "trainer" },

    -- Hemorrhage (Subtlety 21-point talent)
    { name = "Hemorrhage", level = 30, rank = 1, base_cost = 0, icon = "Spell_Shadow_LifeDrain", source = "talent" },
    { name = "Hemorrhage", level = 46, rank = 2, base_cost = 13000, icon = "Spell_Shadow_LifeDrain", source = "talent" },
    { name = "Hemorrhage", level = 58, rank = 3, base_cost = 20000, icon = "Spell_Shadow_LifeDrain", source = "talent" },

    -- Instant Poison
    { name = "Instant Poison", level = 20, rank = 1, base_cost = 2000, icon = "Ability_Poisons", source = "trainer" },
    { name = "Instant Poison", level = 28, rank = 2, base_cost = 7000, icon = "Ability_Poisons", source = "trainer" },
    { name = "Instant Poison", level = 36, rank = 3, base_cost = 13000, icon = "Ability_Poisons", source = "trainer" },
    { name = "Instant Poison", level = 44, rank = 4, base_cost = 23000, icon = "Ability_Poisons", source = "trainer" },
    { name = "Instant Poison", level = 52, rank = 5, base_cost = 35000, icon = "Ability_Poisons", source = "trainer" },
    { name = "Instant Poison", level = 60, rank = 6, base_cost = 42000, icon = "Ability_Poisons", source = "trainer" },

    -- Kick
    { name = "Kick", level = 12, rank = 1, base_cost = 600, icon = "Ability_Kick", source = "trainer" },
    { name = "Kick", level = 26, rank = 2, base_cost = 5000, icon = "Ability_Kick", source = "trainer" },
    { name = "Kick", level = 42, rank = 3, base_cost = 18000, icon = "Ability_Kick", source = "trainer" },
    { name = "Kick", level = 58, rank = 4, base_cost = 40000, icon = "Ability_Kick", source = "trainer" },

    -- Kidney Shot
    { name = "Kidney Shot", level = 30, rank = 1, base_cost = 8000, icon = "Ability_Rogue_KidneyShot", source = "trainer" },
    { name = "Kidney Shot", level = 50, rank = 2, base_cost = 32000, icon = "Ability_Rogue_KidneyShot", source = "trainer" },

    -- Mind-numbing Poison
    { name = "Mind-numbing Poison", level = 24, rank = 1, base_cost = 4000, icon = "Spell_Nature_NullifyDisease", source = "trainer" },
    { name = "Mind-numbing Poison", level = 38, rank = 2, base_cost = 14000, icon = "Spell_Nature_NullifyDisease", source = "trainer" },
    { name = "Mind-numbing Poison", level = 52, rank = 3, base_cost = 35000, icon = "Spell_Nature_NullifyDisease", source = "trainer" },

    -- Pick Lock
    { name = "Pick Lock", level = 16, rank = 1, base_cost = 1500, icon = "Spell_Nature_MoonKey", source = "trainer" },

    -- Pick Pocket
    { name = "Pick Pocket", level = 4, rank = 1, base_cost = 100, icon = "INV_Misc_Bag_11", source = "trainer" },

    -- Poisons (skill)
    { name = "Poisons", level = 20, rank = 1, base_cost = 0, icon = "Trade_BrewPoison", source = "quest" },

    -- Premeditation (Subtlety 31-point talent)
    { name = "Premeditation", level = 40, rank = 1, base_cost = 0, icon = "Spell_Shadow_Possession", source = "talent" },

    -- Preparation (Subtlety 21-point talent)
    { name = "Preparation", level = 30, rank = 1, base_cost = 0, icon = "Spell_Shadow_AntiShadow", source = "talent" },

    -- Riposte (Combat 11-point talent)
    { name = "Riposte", level = 20, rank = 1, base_cost = 0, icon = "Ability_Warrior_Challange", source = "talent" },

    -- Rupture
    { name = "Rupture", level = 20, rank = 1, base_cost = 2000, icon = "Ability_Rogue_Rupture", source = "trainer" },
    { name = "Rupture", level = 28, rank = 2, base_cost = 7000, icon = "Ability_Rogue_Rupture", source = "trainer" },
    { name = "Rupture", level = 36, rank = 3, base_cost = 13000, icon = "Ability_Rogue_Rupture", source = "trainer" },
    { name = "Rupture", level = 44, rank = 4, base_cost = 23000, icon = "Ability_Rogue_Rupture", source = "trainer" },
    { name = "Rupture", level = 52, rank = 5, base_cost = 35000, icon = "Ability_Rogue_Rupture", source = "trainer" },
    { name = "Rupture", level = 60, rank = 6, base_cost = 42000, icon = "Ability_Rogue_Rupture", source = "trainer" },

    -- Safe Fall (passive)
    { name = "Safe Fall", level = 40, rank = 1, base_cost = 15000, icon = "INV_Feather_01", source = "trainer" },

    -- Sap
    { name = "Sap", level = 10, rank = 1, base_cost = 400, icon = "Ability_Sap", source = "trainer" },
    { name = "Sap", level = 28, rank = 2, base_cost = 7000, icon = "Ability_Sap", source = "trainer" },
    { name = "Sap", level = 48, rank = 3, base_cost = 28000, icon = "Ability_Sap", source = "trainer" },

    -- Sinister Strike (innate)
    { name = "Sinister Strike", level = 1, rank = 1, base_cost = 0, icon = "Spell_Shadow_RitualOfSacrifice", source = "class" },
    { name = "Sinister Strike", level = 6, rank = 2, base_cost = 100, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },
    { name = "Sinister Strike", level = 14, rank = 3, base_cost = 900, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },
    { name = "Sinister Strike", level = 22, rank = 4, base_cost = 3000, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },
    { name = "Sinister Strike", level = 30, rank = 5, base_cost = 8000, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },
    { name = "Sinister Strike", level = 38, rank = 6, base_cost = 14000, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },
    { name = "Sinister Strike", level = 46, rank = 7, base_cost = 26000, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },
    { name = "Sinister Strike", level = 54, rank = 8, base_cost = 36000, icon = "Spell_Shadow_RitualOfSacrifice", source = "trainer" },

    -- Slice and Dice
    { name = "Slice and Dice", level = 10, rank = 1, base_cost = 400, icon = "Ability_Rogue_SliceDice", source = "trainer" },
    { name = "Slice and Dice", level = 42, rank = 2, base_cost = 18000, icon = "Ability_Rogue_SliceDice", source = "trainer" },

    -- Sprint
    { name = "Sprint", level = 10, rank = 1, base_cost = 400, icon = "Ability_Rogue_Sprint", source = "trainer" },
    { name = "Sprint", level = 34, rank = 2, base_cost = 12000, icon = "Ability_Rogue_Sprint", source = "trainer" },
    { name = "Sprint", level = 58, rank = 3, base_cost = 40000, icon = "Ability_Rogue_Sprint", source = "trainer" },

    -- Stealth (innate)
    { name = "Stealth", level = 1, rank = 1, base_cost = 0, icon = "Ability_Stealth", source = "class" },
    { name = "Stealth", level = 20, rank = 2, base_cost = 2000, icon = "Ability_Stealth", source = "trainer" },
    { name = "Stealth", level = 40, rank = 3, base_cost = 15000, icon = "Ability_Stealth", source = "trainer" },
    { name = "Stealth", level = 60, rank = 4, base_cost = 42000, icon = "Ability_Stealth", source = "trainer" },

    -- Vanish
    { name = "Vanish", level = 22, rank = 1, base_cost = 3000, icon = "Ability_Vanish", source = "trainer" },
    { name = "Vanish", level = 42, rank = 2, base_cost = 18000, icon = "Ability_Vanish", source = "trainer" },

    -- Wound Poison
    { name = "Wound Poison", level = 32, rank = 1, base_cost = 10000, icon = "INV_Misc_Herb_16", source = "trainer" },
    { name = "Wound Poison", level = 40, rank = 2, base_cost = 15000, icon = "INV_Misc_Herb_16", source = "trainer" },
    { name = "Wound Poison", level = 48, rank = 3, base_cost = 28000, icon = "INV_Misc_Herb_16", source = "trainer" },
    { name = "Wound Poison", level = 56, rank = 4, base_cost = 38000, icon = "INV_Misc_Herb_16", source = "trainer" },
}